// Code generated by protoc-gen-go. DO NOT EDIT.
// source: caseylucas/second/v1/second_api.proto

package secondv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddWidgetRequest struct {
	// When adding a new widget, leave the widget_id, created_at_time and update_at_time blank/default. They will
	// be populated in the response.
	Widget               *Widget  `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWidgetRequest) Reset()         { *m = AddWidgetRequest{} }
func (m *AddWidgetRequest) String() string { return proto.CompactTextString(m) }
func (*AddWidgetRequest) ProtoMessage()    {}
func (*AddWidgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26125ce3c9694c8, []int{0}
}

func (m *AddWidgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWidgetRequest.Unmarshal(m, b)
}
func (m *AddWidgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWidgetRequest.Marshal(b, m, deterministic)
}
func (m *AddWidgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWidgetRequest.Merge(m, src)
}
func (m *AddWidgetRequest) XXX_Size() int {
	return xxx_messageInfo_AddWidgetRequest.Size(m)
}
func (m *AddWidgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWidgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWidgetRequest proto.InternalMessageInfo

func (m *AddWidgetRequest) GetWidget() *Widget {
	if m != nil {
		return m.Widget
	}
	return nil
}

type AddWidgetResponse struct {
	Widget               *Widget  `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWidgetResponse) Reset()         { *m = AddWidgetResponse{} }
func (m *AddWidgetResponse) String() string { return proto.CompactTextString(m) }
func (*AddWidgetResponse) ProtoMessage()    {}
func (*AddWidgetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26125ce3c9694c8, []int{1}
}

func (m *AddWidgetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWidgetResponse.Unmarshal(m, b)
}
func (m *AddWidgetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWidgetResponse.Marshal(b, m, deterministic)
}
func (m *AddWidgetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWidgetResponse.Merge(m, src)
}
func (m *AddWidgetResponse) XXX_Size() int {
	return xxx_messageInfo_AddWidgetResponse.Size(m)
}
func (m *AddWidgetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWidgetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddWidgetResponse proto.InternalMessageInfo

func (m *AddWidgetResponse) GetWidget() *Widget {
	if m != nil {
		return m.Widget
	}
	return nil
}

func init() {
	proto.RegisterType((*AddWidgetRequest)(nil), "caseylucas.second.v1.AddWidgetRequest")
	proto.RegisterType((*AddWidgetResponse)(nil), "caseylucas.second.v1.AddWidgetResponse")
}

func init() {
	proto.RegisterFile("caseylucas/second/v1/second_api.proto", fileDescriptor_b26125ce3c9694c8)
}

var fileDescriptor_b26125ce3c9694c8 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0x4e, 0x2c, 0x4e,
	0xad, 0xcc, 0x29, 0x4d, 0x4e, 0x2c, 0xd6, 0x2f, 0x4e, 0x4d, 0xce, 0xcf, 0x4b, 0xd1, 0x2f, 0x33,
	0x84, 0xb2, 0xe2, 0x13, 0x0b, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x44, 0x10, 0xca,
	0xf4, 0x20, 0x92, 0x7a, 0x65, 0x86, 0x52, 0x8a, 0x58, 0x35, 0x97, 0x67, 0xa6, 0xa4, 0xa7, 0x96,
	0x40, 0x34, 0x2a, 0x79, 0x70, 0x09, 0x38, 0xa6, 0xa4, 0x84, 0x83, 0x85, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0x4c, 0xb8, 0xd8, 0x20, 0x6a, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d,
	0x64, 0xf4, 0xb0, 0x99, 0xae, 0x07, 0xd5, 0x04, 0x55, 0xab, 0xe4, 0xc9, 0x25, 0x88, 0x64, 0x52,
	0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x79, 0x46, 0x19, 0x65, 0x72, 0x71, 0x06, 0x83, 0xe5, 0x1c,
	0x03, 0x3c, 0x85, 0x62, 0xb8, 0x38, 0xe1, 0xe6, 0x0a, 0xa9, 0x61, 0xd7, 0x8f, 0xee, 0x05, 0x29,
	0x75, 0x82, 0xea, 0x20, 0x0e, 0x74, 0xca, 0xe2, 0x92, 0x48, 0xce, 0xcf, 0xc5, 0xaa, 0xda, 0x89,
	0x0f, 0xea, 0x88, 0x82, 0xcc, 0x00, 0x50, 0x58, 0x05, 0x30, 0x46, 0x71, 0x40, 0x24, 0xcb, 0x0c,
	0x17, 0x31, 0x31, 0x3b, 0x07, 0x47, 0xac, 0x62, 0x12, 0x71, 0x46, 0x68, 0x84, 0xa8, 0xd6, 0x0b,
	0x33, 0x3c, 0x85, 0x2c, 0x1c, 0x03, 0x11, 0x8e, 0x09, 0x33, 0x4c, 0x62, 0x03, 0x07, 0xb9, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xbf, 0x18, 0x11, 0xd4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecondAPIClient is the client API for SecondAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecondAPIClient interface {
	// Add a new widget.
	AddWidget(ctx context.Context, in *AddWidgetRequest, opts ...grpc.CallOption) (*AddWidgetResponse, error)
}

type secondAPIClient struct {
	cc *grpc.ClientConn
}

func NewSecondAPIClient(cc *grpc.ClientConn) SecondAPIClient {
	return &secondAPIClient{cc}
}

func (c *secondAPIClient) AddWidget(ctx context.Context, in *AddWidgetRequest, opts ...grpc.CallOption) (*AddWidgetResponse, error) {
	out := new(AddWidgetResponse)
	err := c.cc.Invoke(ctx, "/caseylucas.second.v1.SecondAPI/AddWidget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecondAPIServer is the server API for SecondAPI service.
type SecondAPIServer interface {
	// Add a new widget.
	AddWidget(context.Context, *AddWidgetRequest) (*AddWidgetResponse, error)
}

func RegisterSecondAPIServer(s *grpc.Server, srv SecondAPIServer) {
	s.RegisterService(&_SecondAPI_serviceDesc, srv)
}

func _SecondAPI_AddWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecondAPIServer).AddWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/caseylucas.second.v1.SecondAPI/AddWidget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecondAPIServer).AddWidget(ctx, req.(*AddWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecondAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "caseylucas.second.v1.SecondAPI",
	HandlerType: (*SecondAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWidget",
			Handler:    _SecondAPI_AddWidget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "caseylucas/second/v1/second_api.proto",
}
